=== jdrequena/processvalidator/xsd/pvs/BasicRules_schema.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xsd:schema version="1.0" targetNamespace="http://tigo.com/rules/v1/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:rul="http://tigo.com/rules/v1/schema" xmlns:ent="http://tigo.com/entities/v1/schema" xmlns:add="http://xmlns.tigo.com/AdditionalSchema/V1">
   <xsd:import namespace="http://tigo.com/entities/v1/schema" schemaLocation="BasicEntities_schema.xsd"/>
   <xsd:import namespace="http://xmlns.tigo.com/AdditionalSchema/V1" schemaLocation="../CommonsResources/XSD/AdditionalSchemaV1.xsd"/>
   <xsd:element name="rules" type="rul:rules_array" nillable="true"/>
   <xsd:complexType name="rules_array">
      <xsd:sequence>
         <xsd:element name="rule" type="rul:ruleType" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
   </xsd:complexType>
   <xsd:element name="rule" type="rul:ruleType"/>
   <xsd:complexType name="ruleType">
      <xsd:sequence>
         <xsd:element name="id" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="name" type="xsd:string" minOccurs="0" maxOccurs="1"/>
         <xsd:element ref="add:additionals" minOccurs="0" maxOccurs="1"/>
         <xsd:element name="entities" type="ent:entities_array" minOccurs="0"/>
      </xsd:sequence>
   </xsd:complexType>
</xsd:schema>

=== jdrequena/processvalidator/public_html/Transformation_RulesV2ToRulesV2Custom-Target.xml
<?xml version='1.0' encoding='UTF-8'?>
<rul:rules xmlns:rul="http://tigo.com/rules/v1/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tigo.com/rules/v1/schema file:/E:/Broker/ProcessValidatorV2/xsd/pvs/BasicRules_schema.xsd">
   <rule>
      <id>id118</id>
      <name>name119</name>
      <add:additionals xmlns:add="http://xmlns.tigo.com/AdditionalSchema/V1"/>
      <entities/>
   </rule>
   <rule>
      <id>id135</id>
      <name>name136</name>
      <add:additionals xmlns:add="http://xmlns.tigo.com/AdditionalSchema/V1"/>
      <entities/>
   </rule>
   <rule>
      <id>id152</id>
      <name>name153</name>
      <add:additionals xmlns:add="http://xmlns.tigo.com/AdditionalSchema/V1"/>
      <entities/>
   </rule>
</rul:rules>
