=== jdrequena/processvalidator/xsd/DB_Select_PROCESS_RULES_INFO.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_PROCESS_RULES_INFO" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_PROCESS_RULES_INFO" elementFormDefault="qualified" attributeFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="DB_Select_PROCESS_RULES_INFOInput" type="DB_Select_PROCESS_RULES_INFOInput"/>
   <xs:complexType name="DB_Select_PROCESS_RULES_INFOInput">
      <xs:sequence>
         <xs:element name="processId" type="xs:string" minOccurs="0"/>
         <xs:element name="productId" type="xs:string" minOccurs="0"/>
      </xs:sequence>
   </xs:complexType>
   <xs:element name="DB_Select_PROCESS_RULES_INFOOutputCollection" type="DB_Select_PROCESS_RULES_INFOOutputCollection"/>
   <xs:complexType name="DB_Select_PROCESS_RULES_INFOOutputCollection">
      <xs:sequence>
         <xs:element name="DB_Select_PROCESS_RULES_INFOOutput" type="DB_Select_PROCESS_RULES_INFOOutput" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="DB_Select_PROCESS_RULES_INFOOutput">
      <xs:sequence>
         <xs:element name="RULE_ID" type="xs:string" minOccurs="0"/>
         <xs:element name="NAME" type="xs:string" minOccurs="0"/>
         <xs:element name="DATA_ID" type="xs:string" minOccurs="0"/>
         <xs:element name="CUSTOM_NAME" type="xs:string" minOccurs="0" nillable="true"/>
         <xs:element name="CUSTOM_VALUE" type="xs:string" minOccurs="0" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== jdrequena/processvalidator/public_html/Transformation_RulesInfoToRules-Source.xml
<?xml version='1.0' encoding='UTF-8'?>
<DB_Select_PROCESS_RULES_INFOOutputCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_PROCESS_RULES_INFO file:/E:/Broker/ProcessValidatorV2/xsd/DB_Select_PROCESS_RULES_INFO.xsd" xmlns="http://xmlns.oracle.com/pcbpel/adapter/db/DB_Select_PROCESS_RULES_INFO">
   <DB_Select_PROCESS_RULES_INFOOutput>
      <RULE_ID>RULE_ID1</RULE_ID>
      <NAME>NAME2</NAME>
      <DATA_ID>DATA_ID3</DATA_ID>
      <CUSTOM_NAME>CUSTOM_NAME4</CUSTOM_NAME>
      <CUSTOM_VALUE>CUSTOM_VALUE5</CUSTOM_VALUE>
   </DB_Select_PROCESS_RULES_INFOOutput>
   <DB_Select_PROCESS_RULES_INFOOutput>
      <RULE_ID>RULE_ID1</RULE_ID>
      <NAME>NAME7</NAME>
      <DATA_ID>DATA_ID8</DATA_ID>
      <CUSTOM_NAME>CUSTOM_NAME9</CUSTOM_NAME>
      <CUSTOM_VALUE>CUSTOM_VALUE10</CUSTOM_VALUE>
   </DB_Select_PROCESS_RULES_INFOOutput>
   <DB_Select_PROCESS_RULES_INFOOutput>
      <RULE_ID>RULE_ID11</RULE_ID>
      <NAME>NAME12</NAME>
      <DATA_ID>DATA_ID13</DATA_ID>
      <CUSTOM_NAME>CUSTOM_NAME14</CUSTOM_NAME>
      <CUSTOM_VALUE>CUSTOM_VALUE15</CUSTOM_VALUE>
   </DB_Select_PROCESS_RULES_INFOOutput>
</DB_Select_PROCESS_RULES_INFOOutputCollection>
